### ISSUE TITLE
author contributions?

### ISSUE THREAD

**Issue by corybrunson** [garretrc/ggvoronoi#1]
One author contributed code through Git, and another co-authored the vignette, though i don't doubt that all four credited authors contributed significantly to the package. To address one question from the review, could the documentation or the software paper include a brief note on each author's contribution?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1096)._

**Comment by garretrc** [comment]
Added some high-level descriptions of author/contributor contributions in CONTRIBUTING.md, and included a few words in the README pointing to this change
