### ISSUE TITLE
statement of need

### ISSUE THREAD

**Issue by corybrunson** [garretrc/ggvoronoi#2]
The vignette provides several examples, including two real-world case studies. However, neither the `DESCRIPTION` nor the vignette include a few general sentences on the kinds of problems the package is intended to help users solve (as the software paper does).

Such purpose statement might be included in a central documentation page accessible via `?ggvoronoi`. (See `?ggplot2` for an example.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1096)._

**Comment by garretrc** [comment]
Added some package purpose information from the paper into the readme, and created a new documentation file for ?ggvoronoi with that same information!
