### ISSUE TITLE
Update github installation to reflect devtools/remotes changes.

### ISSUE THREAD

**Issue by trinker** [garretrc/ggvoronoi#7]
When I installed the package from GitHub the repo was not built, likely because the `build_vignettes`  option is no longer part of the *remotes* backend for *devtools* (>= v 2.0.1)).  Also devtools is large so for the case of installing a package all of devtools is not needed, maybe opt for just the remotes version which detools is just reexporting.  Something like:

```
remotes::install_github("garretrc/ggvoronoi", dependencies = TRUE, build_opts = c("--no-resave-data"))
```

**Comment by garretrc** [comment]
Tested and that seems to work better, thanks for the good catch! I've replaced the line in the README with your suggested code.

**Comment by corybrunson** [comment]
I'll start doing this, too! Thanks for the tip, @trinker.
