### ISSUE TITLE
Hyperlinks in README

### ISSUE THREAD

**Issue by trinker** [garretrc/ggvoronoi#8]
It'd be nice to see some hyperinks to outside references as well as internal documents.  For, example when you reference 'deldir' it'd be nice to link to CRAN for ease of reference.  Secondly, when you discuss internal files like:

> To contribute to the package or see past contributions, see the CONTRIBUTING.md file

linking the text to the `CONTRIBUTING.md` file would be pretty nice, especially for someone unfamiliar with packages/GitHub.

**Comment by garretrc** [comment]
Great idea. I'll get on that!

**Comment by garretrc** [comment]
Hyperlinks to R packages and other files in the repository were added to REAMDE and CONTRIBUTING. Also added a hyperlink to the Voronoi diagram wikipedia for any curious individuals
